## Text Splitting from documents - RecursiveCharcter text splitters

This text splitters is the recommended one for generic text. It is parameterized by a list of characters. It tries to split
on them the chunks are small enough. The default list is ["\n\n", "\n", " ", ""]. This has the effect of trying to keep all the paragraphs( and then the sentences , and the words) together as long as possible, as those would generically seem to be the stringest semantically related pieces of text.

- How the text is split: by the list of characters
- How the chunk size is measured: by the number of characters

In [13]:
## reading a pdf
from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader('Pandas_PDF.pdf')
docs = loader.load()

In [14]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
final_documents = splitter.split_documents(docs)
final_documents

[Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 0, 'page_label': '1'}, page_content='2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 1/35\nWhy Pandas\n1. Pandas library provides high perfromance usable data structures and data analysis tools\nfor managing data tables \n2. Supports standard functions to create pivot tables, column or row groupings, plotting\ngraphs, joining tables like SQL, etc. \nBusiness UseCase:'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 0, 'page_label': '1'}, page_content='Let assume that you are working on an airlines data and you want are recieving data\ncontinuously in the form of SQL tables or excel spreadsheets. You have created a detailed report\nfrom the data and the management really likes the key insights you are deriving from data. They\nwant you to send this on the weekly level to the entire team.\nYou can either use SQL or excel spreadsheets to sit and create this every week or you can'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 0, 'page_label': '1'}, page_content='automate the task with a python script using pandas APIs. You can even automate sending the\nemail with python.\nWhat is Pandas\nThere are three basic data structures in the pandas library:\n1. DataFrame: This is the main data structure and it is a 2D table, similar to excel/spreadsheet\ntables with columns names and row labels. \n2. Series: It is a 1D array, similar to a column in excel or excel spreadsheet with column name\nand row labels.'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 0, 'page_label': '1'}, page_content='3. Panel : It is dictionary of dataframes. It is generally not used in practice and we will not be\ndiscussing it in the videos.\nPandas Series\n1. Similar to python list for definition purpose. \n2. For operations purpose, it behaves similar to numpy one-dimensional ndarrays and can be\npassed directly to numpy functions.\nCreating a Series\nIn [3]:\nimport pandas as pd \nimport numpy as np \nIn [2]:\n# Using Python list as series objects \ns = pd.Series([-1.,-1,21,5])'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 1, 'page_label': '2'}, page_content='2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 2/35\n0    -1.0 \n1    -1.0 \n2    21.0 \n3     5.0 \ndtype: float64\nChuck     40 \nDarwin    40 \nElijah    40 \ndtype: int64\nNewton    6 \nChuck     3 \nDarwin    8 \nElijah    9 \ndtype: int64\nChuck     3 \nElijah    9 \ndtype: int64\n0     1 \n1     2 \n2    34 \n3     4 \ndtype: int64\nCharles    6.0 \nChuck     -5.4 \nName: heights, dtype: float64'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 1, 'page_label': '2'}, page_content='Operations on Series\ns \nOut[2]:\nIn [3]:\n# Using python list as index labels and scalar object values \n \ns = pd.Series(40, ["Chuck", "Darwin", "Elijah"]) \ns \nOut[3]:\nIn [4]:\n# Using dictionary with indecies \ndict1 = {"Newton": 6, "Chuck": 3, "Darwin": 8, "Elijah": 9} \ns = pd.Series(dict1) \ns \nOut[4]:\nIn [5]:\n#We can also specify the indicies explicity to control what goes into the series  \ns = pd.Series(dict1, index = ["Chuck", "Elijah"]) \ns \nOut[5]:\nIn [6]:\n# Using numpy array'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 1, 'page_label': '2'}, page_content='#s = pd.Series(np.array([[1,2],[34,4]])) \ns = pd.Series(np.array([1,2,34,4])) \ns \nOut[6]:\nIn [7]:\n# Giving name to the series as  \ns = pd.Series([6, -5.4], index=["Charles", "Chuck"], name="heights") \ns \nOut[7]:\nIn [8]:\n# Use a series in numpy functions. Here we take exponential of the series \nnp.abs(s)'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 2, 'page_label': '3'}, page_content="2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 3/35\nCharles    6.0 \nChuck      5.4 \nName: heights, dtype: float64\nElementwise arithmetic operations on pandas Series are similar to numpy ndarray's:\nCharles    1006.0 \nChuck      1994.6 \nName: heights, dtype: float64\nBroadcasting is similar to numpy. If you add a single number to Series, it is broadcasted\nthroughout the series."),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 2, 'page_label': '3'}, page_content='Charles    1006.0 \nChuck       994.6 \nName: heights, dtype: float64\nThe same is true for all binary operations such as multiplication, division, subtraction or evern\nconditionals operations\nCharles    False \nChuck       True \nName: heights, dtype: bool\nAccessing elements of Series (Indexing)\n1. Each item in a Series object has a unique identifier called the *index label*. \n2. By default, it is the rank of the item in the Series (starting at 0) but you can also set the\nindex labels manually'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 2, 'page_label': '3'}, page_content="3. You can also use the series as a dictionary with manually set indexing as well as integer\nindex like regular list.\n--------------------------------------------------------------------------- \nNameError                                 Traceback (most recent call last) \n<ipython-input-12-630081a5992e> in <module> \n----> 1 s2 \nNameError: name 's2' is not defined\nUsing as a dictionary\n---------------------------------------------------------------------------"),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 2, 'page_label': '3'}, page_content='NameError                                 Traceback (most recent call last) \n<ipython-input-13-05e1d0e8f3e2> in <module> \nOut[8]:\nIn [9]:\ns + np.array([1000,2000]) \nOut[9]:\nIn [10]:\ns + 1000 \nOut[10]:\nIn [11]:\ns < 0 \nOut[11]:\nIn [12]:\ns2 \nIn [13]:\ns2["Chuck"]'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 3, 'page_label': '4'}, page_content='2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 4/35\n----> 1 s2["Chuck"] \nNameError: name \'s2\' is not defined\nUsing as a list with integer index\n--------------------------------------------------------------------------- \nNameError                                 Traceback (most recent call last) \n<ipython-input-14-8755b941c10d> in <module> \n----> 1 s2[1]'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 3, 'page_label': '4'}, page_content='NameError: name \'s2\' is not defined\nTo make it clear when you are accessing by label or by integer location, it is recommended to\nalways use the loc attribute when accessing by label, and the iloc attribute when accessing by\ninteger location:\n--------------------------------------------------------------------------- \nNameError                                 Traceback (most recent call last) \n<ipython-input-15-6a9a5ccf47c3> in <module> \n----> 1 s2.loc["Chuck"]'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 3, 'page_label': '4'}, page_content="NameError: name 's2' is not defined\n--------------------------------------------------------------------------- \nNameError                                 Traceback (most recent call last) \n<ipython-input-16-f5692f3bd256> in <module> \n----> 1 s2.iloc[1] \nNameError: name 's2' is not defined\nSlicing a Series also slices the index labels. This can lead to unexpected values being accessed\nwhen using the default numeric labels, so be careful!"),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 3, 'page_label': '4'}, page_content='--------------------------------------------------------------------------- \nNameError                                 Traceback (most recent call last) \n<ipython-input-17-7aab0de711b6> in <module> \n----> 1 s3 = s2.iloc[1:3] \n      2 print(s3) \n      3 s3.loc["Newtown"] \nNameError: name \'s2\' is not defined\n0    1000 \n1    1001 \n2    1002 \n3    1003 \ndtype: int64\nIn [14]:\ns2[1] \nIn [15]:\ns2.loc["Chuck"] \nIn [16]:\ns2.iloc[1] \nIn [17]:\ns3 = s2.iloc[1:3] \nprint(s3) \ns3.loc["Newtown"] \nIn [18]:'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 3, 'page_label': '4'}, page_content='s2 = pd.Series([1000, 1001, 1002, 1003]) \ns2 \nOut[18]:'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 4, 'page_label': '5'}, page_content='2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 5/35\n1    1001 \n2    1002 \n3    1003 \ndtype: int64\nThe first element has index label 1. The element with index label 0 is absent from the slice\n--------------------------------------------------------------------------- \nKeyError                                  Traceback (most recent call last)'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 4, 'page_label': '5'}, page_content='<ipython-input-20-e4a7d3f28305> in <module> \n----> 1 s2_slice[0] \n~/anaconda3/lib/python3.8/site-packages/pandas/core/series.py in __getitem__(self, k\ney) \n    866         key = com.apply_if_callable(key, self) \n    867         try: \n--> 868             result = self.index.get_value(self, key) \n    869  \n    870             if not is_scalar(result): \n~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_value(sel\nf, series, key)'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 4, 'page_label': '5'}, page_content="4372         k = self._convert_scalar_indexer(k, kind='getitem') \n   4373         try: \n-> 4374             return self._engine.get_value(s, k, \n   4375                                           tz=getattr(series.dtype, 'tz', Non\ne)) \n   4376         except KeyError as e1: \npandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value() \npandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value() \npandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()"),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 4, 'page_label': '5'}, page_content='pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get\n_item() \npandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get\n_item() \nKeyError: 0\nBut we can access elements by integer location using the iloc attribute.\n1001\nSo, we should always use loc and iloc to access Series objects.\nAutomatic alignment\nFor operations involving multiple series pandas automatically aligns items by matching the index\nlabels.\nIn [19]:\ns2_slice = s2[1:]'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 4, 'page_label': '5'}, page_content='s2_slice \nOut[19]:\nIn [20]:\ns2_slice[0] \nIn [21]:\ns2_slice.iloc[0] \nOut[21]:\nIn [22]:\ns2 = pd.Series([231, -23, -99, 100], index=["Newton", "Chuck", "Darwin", "Elijah"])'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 5, 'page_label': '6'}, page_content='2/12/22, 10:07 PM Pandas\nfile:///C:/Users/Anilchoudary R/Desktop/SKILLO_VILLA/Course_Videos/Module_3/Pandas and statistic notebook/Pandas_and_Statistics/Pandas… 6/35\nNewton    231 \nChuck     -23 \nDarwin    -99 \nElijah    100 \ndtype: int64 \nCharles    122 \nDarwin    -312 \nChuck      123 \nElijah     -20 \ndtype: int64 \nCharles      NaN \nChuck      100.0 \nDarwin    -411.0 \nElijah      80.0 \nNewton       NaN \ndtype: float64'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 5, 'page_label': '6'}, page_content='Since Charles is missing from s2 and Newton is missing from s3, these have a NaN result value.\n(ie. Not-a-Number means missing).\nAutomatic alignment is very handy when working with data that may come from various sources\nwith varying structure and missing items. But if you forget to set the right index labels, you can\nhave surprising results:\ns2 = [231 -23 -99 100] \ns5 = [ 100  -10  999 -999] \n0        NaN \n1        NaN \n2        NaN \n3        NaN \nChuck    NaN \nDarwin   NaN \nElijah   NaN'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 5, 'page_label': '6'}, page_content='Newton   NaN \ndtype: float64\nPandas could not align the Series, since their labels do not match at all, hence the full NaN\nresult.\nPlotting a Series\nUsing matplotlib is easy with a Series.plot() call\ns3 = pd.Series([122, -312, 123, -20], index=["Charles", "Darwin", "Chuck", "Elijah"]\nprint(s2) \nprint(s3) \n \ns2 + s3 \nOut[22]:\nIn [23]:\ns5 = pd.Series([100,-10,999,-999]) \nprint("s2 =", s2.values) \nprint("s5 =", s5.values) \n \ns2 + s5 \nOut[23]:\nIn [24]:\n%matplotlib inline'),
 Document(metadata={'producer': 'Skia/PDF m96', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36', 'creationdate': '2022-02-12T16:37:04+00:00', 'moddate': '2022-02-12T16:37:04+00:00', 'source': 'Pandas_PDF.pdf', 'total_pages': 35, 'page': 5, 'page_label': '6'}, page_content='import matplotlib.pyplot as plt \n \npressure = [2,6.1,6.1,5.7,4.4,5.1,6.1,6,.5,.2,4.7,4.1,3.9,3.5] \n \ns7 = pd.Series(pressure, name="Pressure")'),

In [ ]:
from langchain_text_splitters import HTMLHeaderTextSplitter

html_string = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Header Text Splitter Test</title>
</head>
<body>
    <h1>Welcome to the Homepage</h1>
    <p>This is a sample paragraph under H1.</p>

    <h2>About Us</h2>
    <p>We are a team of developers.</p>

    <h3>Our Mission</h3>
    <p>To build useful tools.</p>

    <h4>Team Members</h4>
    <ul>
        <li>Alice</li>
        <li>Bob</li>
    </ul>

    <h5>Contact</h5>
    <p>Email: example@example.com</p>

    <h6>Disclaimer</h6>
    <p>All information is for testing purposes.</p>

    <div>
        <h2>Another Section</h2>
        <p>Content inside a div block.</p>
    </div>
</body>
</html>
"""

In [18]:
header_to_split_on=[
    ("h1","Header 1"),
    ("h2", "Header 2"),
    ("h3","Header 3")
]

html_splitter = HTMLHeaderTextSplitter(header_to_split_on)
html_header_splits = html_splitter.split_text(html_string)
html_header_splits

[Document(metadata={'Header 1': 'Welcome to the Homepage'}, page_content='Welcome to the Homepage'),
 Document(metadata={'Header 1': 'Welcome to the Homepage'}, page_content='This is a sample paragraph under H1.'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'About Us'}, page_content='About Us'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'About Us'}, page_content='We are a team of developers.'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'About Us', 'Header 3': 'Our Mission'}, page_content='Our Mission'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'About Us', 'Header 3': 'Our Mission'}, page_content='To build useful tools.  \nTeam Members  \nAlice  \nBob  \nContact  \nEmail: example@example.com  \nDisclaimer  \nAll information is for testing purposes.'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'Another Section'}, page_content='Another Section'),
 Document(metadata={'Header 1': 'Welcome to the Homepage', 'Header 2': 'Another Section'}, page_content='Content inside a div block.')]